import type { Metadata } from "next";
import {
  Bitcount_Prop_Single,
  Mozilla_Headline,
  JetBrains_Mono,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import { ThemeProvider } from "@/components/theme/theme-provider";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

const bitcount = Bitcount_Prop_Single({
  subsets: ["latin"],
  variable: "--font-bitcount-prop-single",
});

const mozillaHeadline = Mozilla_Headline({
  subsets: ["latin"],
  variable: "--font-mozilla-headline",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        "font-mono",
        bitcount.variable,
        jetbrainsMono.variable,
        mozillaHeadline.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
